version: "3.9"

services:
  postgres:
    image: postgres:13-alpine
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: Mypassword
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"